### ISSUE TITLE
Installation contains an additional 'models' directory

### ISSUE THREAD

**Issue by jongarry** [fcakyon/yolov5-pip#1]
Hi there,

While including this package in a project I noticed that an additional 'models' directory gets installed with yolov5. This causes pathing problems when using this package in a project that also contains a models directory:

![Screenshot from 2021-02-19 16-01-00](https://user-images.githubusercontent.com/23202083/108561384-2c79b280-72cc-11eb-8cce-b445a8d4da05.png)

$ pip uninstall yolov5
Found existing installation: yolov5 4.0.3
Uninstalling yolov5-4.0.3:
  Would remove:
    /home/.../miniconda3/lib/python3.7/site-packages/models/*  <--- This contains the same files as yolov5/models/
    /home/.../miniconda3/lib/python3.7/site-packages/yolov5-4.0.3.dist-info/*
    /home/.../miniconda3/lib/python3.7/site-packages/yolov5/*

**Comment by fcakyon** [comment]
It is necessary since ultralytics/yolov5 model loading requires models folder to be in path. If I remove models directory, it wouldnt be possible to load yolov5 weights. If you find a better workaround, I would gladly implement it.
