### ISSUE TITLE
models/*.yaml files not downloaded when installing from pip

### ISSUE THREAD

**Issue by FraPochetti** [fcakyon/yolov5-pip#10]
Hi, 
thanks a lot for your work first of all!

So, when installing from `pip install yolov5`, I noticed that the `yolov5/models/*.yaml` files are not downloaded.
I think this is because you are missing `recursive-include yolov5/models *` from your `MANIFEST.ini`, e.g. you just include whatever is in the `data` directory ([here](https://github.com/fcakyon/yolov5-pip/blob/72c66908fcc6aa03d3dfc67c53cba4115f94f7e8/MANIFEST.in#L11)).
Does this make sense?

**Comment by fcakyon** [comment]
You are right, will be fixed in the next release.

**Comment by fcakyon** [comment]
Should be fixed with v4.0.12. Try `pip install -U yolov5`.

**Comment by FraPochetti** [comment]
Thanks a lot!
