### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement sahi>=0.9.1

### ISSUE THREAD

**Issue by MetehanYasar11** [fcakyon/yolov5-pip#120]
While installing yolov5 with $ pip install yolov5==6.1.3 with Jetson AGX

it retruns ;

ERROR: Could not find a version that satisfies the requirement sahi>=0.9.1 (from yolov5) (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.4.0, 0.4.1, 0.4.2, 0.4.3)
ERROR: No matching distribution found for sahi>=0.9.1

May be sahi>=0.9.1 must be changed into sahi>=0.4.3 in the requirements.txt

I will try this and update this comment...

when I install with $ pip install yolov5 
it installs yolov5 6.0.4 which does not support .engine export... 

Also thanks for the awesome job!

**Comment by fcakyon** [comment]
@MetehanYasar11 thanks for your intrest!

What is python version? Starting from 6.0.5, python 3.5 support is dropped. You can try to update this line to see if it can be installed on python 3.5 environment: https://github.com/fcakyon/yolov5-pip/blob/6ccf6148db1d0aa3869188e738f98a071eb5e342/setup.py#L36

**Comment by MetehanYasar11** [comment]
Thaks for reply, I use jetpack 4.5 on jetson xavier agx. So that I can use python 3.6.9 with tensorRT 7. With sahi>=0.4.3, I passed the error above but stuck in tensorRT 8 requirement for creating engine... 

I need to flash jetpack 5 to the device which has tensorRT 8 and python 3.9.
