### ISSUE TITLE
Use of albumentations

### ISSUE THREAD

**Issue by QazyBi** [fcakyon/yolov5-pip#127]
Hi, thank you for the repo!

I was wondering if it is possible to use augmentations from albumentations library to train yolov5 model?

I know that original yolov5 authors provided such option as stated [here](https://github.com/ultralytics/yolov5/pull/3882). Which is manually editing file with augmentations. However, this repo creates a package and it is not feasible to edit code of the package.

**Comment by kadirnar** [comment]
Why are these parameters turned off?
https://github.com/fcakyon/yolov5-pip/blob/main/yolov5/train.py#L579

**Comment by fcakyon** [comment]
@QazyBi if you have any design suggestion to add albumentations support for this package, I would be glad. Currently this package does not support that.
