### ISSUE TITLE
No module named 'yolov5.utils.dataloaders'

### ISSUE THREAD

**Issue by wasdee** [fcakyon/yolov5-pip#129]
The lib is missing the api 'yolov5.utils.dataloaders'

**Comment by fcakyon** [comment]
Why should it include it? What is your use case? I am not having any errors using any usage mentioned in the readme.

**Comment by wasdee** [comment]
It is a function use in the `detect.py` the official latest detection script. Thus, I am not able to run the scipt.

2nd, it is a public api, not internal ones. e.g. namespace start with underscore.

**Comment by wasdee** [comment]
My codebase removed the dataloaders from `detect.py`. 

Feel free to keep it.

**Comment by fcakyon** [comment]
The latest updates from the original source are not present in this repo. This repo follows from behind (generally 2-3 months back). 

Is the dataloaders module recently added?

**Comment by wasdee** [comment]
yep. it recently added.

**Comment by fcakyon** [comment]
Once I find some free time I will update the source to latest 👍

**Comment by fcakyon** [comment]
@wasdee I have just updated the repo to include the latest updates from ultralytics: https://github.com/fcakyon/yolov5-pip/releases/tag/6.1.7
