### ISSUE TITLE
pycocotools-fix error on Windows

### ISSUE THREAD

**Issue by borijang** [fcakyon/yolov5-pip#13]
I can't install this via pip because of pycocotools-fix on Windows. It fails when trying to build wheel for it.
It would be great if this lib is optional, as I already have pycocotools installed on my environment.

**Comment by fcakyon** [comment]
@borijang you are definitely right, i will push a proper fix today.

**Comment by fcakyon** [comment]
@borijang it is fixed with `v4.0.13`.

please try `pip install -U yolov5`
