### ISSUE TITLE
yolov5.utils.datasets module was renamed to yolov5.utils.dataloaders

### ISSUE THREAD

**Issue by pelennor** [fcakyon/yolov5-pip#132]
Hello.
From ultralytics/yolov5 at this [commit](https://github.com/ultralytics/yolov5/tree/84e7748564f83ba04601770f17a38cc55e6be661) that is based on yolov5-pip v6.1.7, yolov5.utils.datasets module has been renamed since this [commit](https://github.com/ultralytics/yolov5/commit/9d8ed37df77e4e06a1b63cbf51785ec91557bf3d)(it is not officially released yet at least v6.1, but branch v7.0 includes it)
However, your repo has both datasets and dataloaders modules too.
It can confuse some users and auto code completion of IDE(such as PyCharm)
So, it would better sync with ultralytics/yolov5 to avoid ambiguity

**Comment by fcakyon** [comment]
@pelennor thanks for spotting this issue! Should be fixed with `v6.1.8`
