### ISSUE TITLE
yolov5 val working directory error

### ISSUE THREAD

**Issue by fireinice** [fcakyon/yolov5-pip#150]
after installing the package and run 
```bash
yolov5 val test.yaml --weights yolo.pt --imgsz 192 --task test
```

an exception about 

dataset not found

as some logging, it shows the cli script will use package installed directory as the working dir.
since the path in yaml is relative, it won't work.

**Comment by fcakyon** [comment]
Hello @fireinice, can you please post the full error trace?

**Comment by fireinice** [comment]
I'm not using coco yaml but a customized valid yaml:
```yaml
path: train_data
train: images/train
val: images/val
test: images/test
nc: 3
names: [name1, name2, name3 ]
```
and it will try to load data from /home/fireinice/.virtualenvs/myvirtual/lib/python3.9/site-packages/yolov5/
which is where the package intalled
```
Dataset not found ⚠️, missing paths ['/home/fireinice/.virtualenvs/myvirtual/lib/python3.9/site-packages/yolov5/train_data/images/val']
Traceback (most recent call last):
  File "/home/zigler/work/cavy_pipeline/train_script/val.py", line 426, in <module>
    main()
  File "/home/zigler/work/cavy_pipeline/train_script/val.py", line 400, in main
    run(**vars(opt))
  File "/home/zigler/.virtualenvs/circuit/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zigler/work/cavy_pipeline/train_script/val.py", line 167, in run
    data = check_dataset(data)  # check
  File "/home/zigler/.virtualenvs/circuit/lib/python3.9/site-packages/yolov5/utils/general.py", line 492, in check_dataset
    raise Exception(emojis('Dataset not found ❌'))
Exception: Dataset not found ❌
```

by some code digging, the problem is caused by the code below
```python   
if not path.is_absolute():
       path = (ROOT / path).resolve()
```

located on utils/general.py L456

**Comment by fcakyon** [comment]
If you want to use custom daya yaml, you have to provide it as `--data test.yaml`. Have you tried that? 

Your cli sample from first comment is not valid.

**Comment by fireinice** [comment]
yes, I've tried, after commet the codes above ,both work. if not, neither work

**Comment by fcakyon** [comment]
You say that after commenting out the `utils/general line 456`, its fixed, right?

If yes, I will look into it 👍

**Comment by fireinice** [comment]
yes
and by the codes
```python
FILE = Path(__file__).resolve()
ROOT = FILE.parents[1]  # YOLOv5 root directory
```
located on the same file make the root as where the main script located.

I see the two lines are from yolov5 codes. 
by the usage of yolov5, it makes sense since the yolov5 detect.py/val.py/detect.py is always the ROOT(working) directory, and people work around in that directory directly pull from git. however when we install the package, the directory became the directory where the package installed, which makes the cli could not find the relative path.

we have to find a way to work around the codes.

**Comment by fcakyon** [comment]
> yes and by the codes
> 
> ```python
> FILE = Path(__file__).resolve()
> ROOT = FILE.parents[1]  # YOLOv5 root directory
> ```
> 
> located on the same file make the root as where the main script located.
> 
> I see the two lines are from yolov5 codes. by the usage of yolov5, it makes sense since the yolov5 detect.py/val.py/detect.py are always the ROOT(working) directory, and people work around in that directory directly pull from git. however when we install the package, the directory became the directory where the package installed, which makes the cli could not find the relative path.
> 
> we have to find a way to work around the codes.

No, this is the expected behavior. Assume that the user did not provide any `.hyp` config or `data.yaml` or model config file, then this yolov5 package should use the default files located under pip directory. So using the pip directory as root is expected and necessary.

If a user wants to provide a custom path, then he/she should provide the paths as absolute paths.

**Comment by fireinice** [comment]
but the yolov5 configuration recommended use relative path in configuration. and with relative path it is easy to transfer data from machine to machine. So the package behavior is different from yolov5. maybe we can fall back to ROOT directory if IT DID MISS something which sounds better by my opnion.

**Comment by fireinice** [comment]
the codes seem related to this PR https://github.com/ultralytics/yolov5/pull/6489

**Comment by fcakyon** [comment]
> the codes seem related to this PR [ultralytics/yolov5#6489](https://github.com/ultralytics/yolov5/pull/6489)

Yes you are rights, this update is not necessary for this repo. 

I created a PR reverting this update: https://github.com/fcakyon/yolov5-pip/pull/151
