### ISSUE TITLE
"TypeError: random_perspective() got an unexpected keyword argument 'return_seg'" when using custom hyp file in segmentation training

### ISSUE THREAD

**Issue by GiovanniNova** [fcakyon/yolov5-pip#152]
` File "/usr/local/lib/python3.7/dist-packages/yolov5/utils/segment/dataloaders.py", line 152, in __getitem__
    return_seg=True,
TypeError: random_perspective() got an unexpected keyword argument 'return_seg'`

**Comment by fcakyon** [comment]
@GiovanniNova can you be more specific? What was your command?

**Comment by GiovanniNova** [comment]
This doesnt work and throws the error mentioned:
`yolov5 segment train --img 640 --batch 16 --epochs 300 --data table_detect.yaml --hyp hyp.table_detect.yaml --weights yolov5s-seg.pt`

But removing the --hyp parameters works just fine
`yolov5 segment train --img 640 --batch 16 --epochs 300 --data table_detect.yaml  --weights yolov5s-seg.pt`

A workaround is adding 'return_seg=False' to random_perspective which is defined at "yolov5\utils\segment\augmentations.py"

**Comment by fcakyon** [comment]
There is no return_seg argument in the original repo, why should we add it? https://github.com/ultralytics/yolov5/blob/c8e52304cf5c34653570c5c3953ba061bc33c1af/utils/segment/augmentations.py#L25

Am I missing something?

**Comment by fcakyon** [comment]
@GiovanniNova this PR fixes this bug: https://github.com/fcakyon/yolov5-pip/pull/153
