### ISSUE TITLE
YouTube Bug Fix

### ISSUE THREAD

**Issue by StuffByAndrew** [fcakyon/yolov5-pip#18]
It seems like the [Youtube Bug Fix](https://github.com/ultralytics/yolov5/pull/2818) from the main yolov5 repo has not been applied here as well causing some scripts to fail. 

For example with:
 `$ yolo_detect --source 0`

**Comment by fcakyon** [comment]
@StuffByAndrew will be pushed to pypi once the checks pass: https://github.com/fcakyon/yolov5-pip/pull/19

**Comment by fcakyon** [comment]
try `pip install -U yolov5`

**Comment by StuffByAndrew** [comment]
It works! Thanks!
