### ISSUE TITLE
How can I get the result in string format

### ISSUE THREAD

**Issue by Olalaye** [fcakyon/yolov5-pip#32]
How can I get the result in string format?

I installed the package and made predictions, but how do I get the results in string format?

Please give me some guidance.

**Comment by Olalaye** [comment]
I got what I wanted from `results.pandas().xyxy`
```
results.pandas().xyxy
results.pandas().xyxyn
results.pandas().xywh
results.pandas().xywhn
```
It's a good idea to keep all the results in pd.dataframe.

But the project seems to lack information on how to use it.

**Comment by fcakyon** [comment]
@Olalaye thanks for providing your solution. It will be added to main readme!

**Comment by Olalaye** [comment]
@fcakyon Your README is well written, but is more suitable for running this project than for calling the yolov5 package, in my opinion.
