### ISSUE TITLE
check_requirements(...) prevents functionality 

### ISSUE THREAD

**Issue by ivanzvonkov** [fcakyon/yolov5-pip#36]
The original repo has a check_requirements(...) [function](https://github.com/ultralytics/yolov5/blob/831773f5a23926658ee76459ce37550643432123/utils/general.py#L148) to check for a requirements.txt 

All functions that call `check_requirements(...)` 
https://github.com/ultralytics/yolov5/search?q=check_requirements
will fail in the pip package context.

For example:
```python
from yolov5 import hubconf
hubconf.custom("<any path>")
```
Results in:
```
requirements: /opt/anaconda3/envs/dev/lib/python3.9/site-packages/yolov5/requirements.txt not found, check failed.
```

Has anyone found a work around for this?

**Comment by fcakyon** [comment]
@ivanzvonkov actually you shouldnt be using hubconf in this package. You can directly:
```python
import yolov5
model = yolov5.load(`yolov5s6.pt`)
```

**Comment by fcakyon** [comment]
@ivanzvonkov in lates version (v5.0.7) `check_requirements` flag is removed from all scripts.
`pip install -U yolov5` to install up-to-date version.

**Comment by ivanzvonkov** [comment]
@fcakyon Thanks for the lightning quick update!
