### ISSUE TITLE
Load multiple weights for ensemble

### ISSUE THREAD

**Issue by ryanfont80** [fcakyon/yolov5-pip#38]
Is there any ability to load multiple weights to create an ensemble like in the original Yolov5 repository? 

Thanks!

**Comment by fcakyon** [comment]
@ryanfont80 how does the original repo handle that? Most probably it can be done the same way.

**Comment by ryanfont80** [comment]
You load them as a list say ['weight1.pt', 'weights2.pt', 'weights3.pt']

But when I try that method in your Repo it is not a valid data type and causes errors. Specifically it causes : 

  File "sahi_test.py", line 26, in <module>
    predict(
  File "C:\Users\Ryan\anaconda3_2020\lib\site-packages\sahi\predict.py", line 383, in predict
    detection_model.load_model()
  File "C:\Users\Ryan\anaconda3_2020\lib\site-packages\sahi\model.py", line 373, in load_model
    category_mapping = {str(ind): category_name for ind, category_name in enumerate(self.category_names)}
  File "C:\Users\Ryan\anaconda3_2020\lib\site-packages\sahi\model.py", line 413, in category_names
    return self.model.names
AttributeError: 'NoneType' object has no attribute 'names'

**Comment by ryanfont80** [comment]
however if you use just 'weight1.pt' individually it works perfectly fine... so something in the string/list data type is causing the issue.  I cannot seem to find any guideline either for the model.load where an ensemble is used.

**Comment by fcakyon** [comment]
@ryanfont80 `sahi` package is different than `yolov5` package. `sahi` does not have ensemble support but `yolov5` has.

you have to use `yolov5_detect` command from cli or `yolov5.detect()` method in python for ensemble support. check this page for ensemble tutorial: https://github.com/ultralytics/yolov5/issues/318
