### ISSUE TITLE
Return inference value directly instead of saving in text files in a project

### ISSUE THREAD

**Issue by RAbraham** [fcakyon/yolov5-pip#42]
Hi,
Sorry as though there is good documentation, I don't know how to fit it to my use case, I think. My context is that I'm trying to run a yolov5 model on a server doing predictions via an API.

My data scientist has given me a weights file `model.pt` which is trained on our data. how do I
- load that model only once during server initialization
- pass a list of images in memory instead of a folder
- return the value directly instead of accessing text files in a project folder.

I started with `detect` 
```
res = detect.run(nosave=True, save_conf=True,save_txt=True, project=str(dirpath), source=img_url, weights=weights, conf_thres=0.25, imgsz=640, device="cpu")

```
but 
- `res` is None. The predictions are saved in a txt file which I have to pick up and read. Could I have a simpler interface which just returns values as a dictionary for e.g. or whatever you prefer
- I have to pass the `weights` file each time which means it loads up the file for every execution which could add up when there are multiple api requests?
- If I have a batch of images, I have to create a temp folder and put them there? Thats fine... but is there a way of passing  a in-memory list of images in bytes. This is not a big issue. just curious

I looked at `predict` but it says
```
model_path = "yolov5/weights/yolov5s.pt" # it automatically downloads yolov5s model to given path


# init yolov5 model
yolov5 = YOLOv5(model_path, device)
# perform inference
...
results = yolov5.predict(image1)
```
I don't want to use the yolov5s model but my own model. So, I'm not sure how to do that with `predict`.

If I have missed something, please let me know.

**Comment by fcakyon** [comment]
Hello @RAbraham, thanks a lot for your interest in the yolov5 package!

Assume your custom model file is located under `runs/exp1/weights/best.pt`. Then you can load it as:

```python
import yolov5

# load model
model = yolov5.load('runs/exp1/weights/best.pt', device='cuda:0')
```

Then you can perform inference with the loaded model as:

```python
# set image path
img = 'images/image.jpg'

# perform inference with 1280 input size
results = model(img, size=1280)

# parse results
predictions = results.pred[0]
boxes = predictions[:, :4] # x1, x2, y1, y2
scores = predictions[:, 4]
categories = predictions[:, 5]
```

You can also perform batch inference by giving a list of images:
```python
# set image path
img1 = 'images/image1.jpg'
img2 = 'images/image2.jpg'

# perform inference with 1280 input size
results = model([img1, img2], size=1280)

# parse results
predictions = results.pred[0]
boxes = predictions[:, :4] # x1, x2, y1, y2
scores = predictions[:, 4]
categories = predictions[:, 5]
```

Feel free to ask if you have any further questions!

**Comment by fcakyon** [comment]
@RAbraham instead of giving image paths, you can feed anything as input to the model:
```python
        #   file:       imgs = 'data/images/zidane.jpg'  # str or PosixPath
        #   URI:             = 'https://ultralytics.com/images/zidane.jpg'
        #   OpenCV:          = cv2.imread('image.jpg')[:,:,::-1]  # HWC BGR to RGB x(640,1280,3)
        #   PIL:             = Image.open('image.jpg') or ImageGrab.grab()  # HWC x(640,1280,3)
        #   numpy:           = np.zeros((640,1280,3))  # HWC
        #   torch:           = torch.zeros(16,3,320,640)  # BCHW (scaled to size=640, 0-1 values)
        #   multiple:        = [Image.open('image1.jpg'), Image.open('image2.jpg'), ...]  # list of images

results = model(imgs)
```

**Comment by RAbraham** [comment]
that's great. Thanks!
