### ISSUE TITLE
Yolov5 Kurulumu

### ISSUE THREAD

**Issue by kadirnar** [fcakyon/yolov5-pip#55]
Merhabalar,

Windows da anaconda üzerinden kurulum yapınca böyle bir hata alıyorum. Ubuntu da kurulum yaptığımda hata almıyorum. Yardımcı olabilir misiniz?

![yolov5-pip](https://user-images.githubusercontent.com/36204372/139930058-a75e309a-7ce3-4a67-9b48-d414a1cfd32b.png)

Spyder sürümlerim:

Ubuntu: 5.0
Windwos: 5.1

**Comment by fcakyon** [comment]
Merhaba @kadirnar, `pycocotools` derleyebilmek icin Windows bilgisayarinda Visual Studio 14.0 veya daha ust surum kurulu olmasi gerekiyor. Ayrica C++ derleyici paketini kurman gerekiyor. Su videonun 8:45'ine kadar olan stepleri takip edebilirsin: https://www.youtube.com/watch?v=URWeg5PKYUM

Ubuntu'da default olarak g++ derleyici mevcut oldugu icin bu hata sadece Windows'ta aliniyor.
