### ISSUE TITLE
Using model with onnx weights

### ISSUE THREAD

**Issue by jorgegarcia197** [fcakyon/yolov5-pip#58]
Wondering if I can use this library with the onnx weights exported from the trained model. 

More especifically, if I can use the load it and use the detect method with onnx. 

I am currently trying to do it but getting the following error

![image](https://user-images.githubusercontent.com/46676143/141843099-05fde9b8-bf4f-4f9e-8cee-a9cc1e236b3f.png)

and this is my current code 

```python
from yolov5 import YOLOv5
from PIL import Image

# set model params
model_path = "ObjectDetection/models/best.onnx"
device = "cuda:0"  # or "cpu"


image1 = Image.open("randomimage.jpg")
yolov5 = YOLOv5(model_path, device)


results = yolov5.predict(image1)
results.show()
```

**Comment by fcakyon** [comment]
@jorgegarcia197 thanks a lot for your interest in the project!

Unfortunately yolov5 predict api does not support onnx inference. You have to use `yolov5.detect` api for onnx inference (similar to original yolov5 repo):
```python
from yolov5 import detect

detect.run(weights="ObjectDetection/models/best.onnx", imgsz=640)
```

You can follow this issue for more detail: https://github.com/fcakyon/yolov5-pip/issues/53
