### ISSUE TITLE
problem reading yaml 

### ISSUE THREAD

**Issue by LJ-00** [fcakyon/yolov5-pip#65]
Hello, 
Could you help me with the following: There is a problem when I try to use any yaml document to train: 

  File "C:\Users\anaconda3\envs\torch_YOLOV5\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 275: character maps to <undefined>

**Comment by fcakyon** [comment]
@LJ-00  It seems like there are some special characters in your yaml that is causing some issues. Would you mind uploading your yaml file so that I can recreate this issue? At the moment I can run all scripts with my yaml files.

**Comment by LJ-00** [comment]
Thanks for your quick reply. 

These are the contents:


# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# COCO 2017 dataset http://cocodataset.org
# Example usage: python train.py --data coco.yaml
# parent
# ├── yolov5
# └── datasets
#     └── coco  ← downloads here

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#path: D:/datasets/data # dataset root dir

train: D:\datasets\data\images  
val: D:\datasets\data\images   
test: D:\datasets\data\testing 

# Classes
nc: 1  # number of classes
names: ['door']  # class names

**Comment by fcakyon** [comment]
You have to update the slashes as `/`.

```yaml
train: D:/datasets/data/images
val: D:/datasets/data/images
test: D:/datasets/data/testing

nc: 1 # number of classes
names: ['door'] # class names
```

**Comment by LJ-00** [comment]
Hello 
I did that but it didn't work. I was using the yaml files from the ultranalitics yolov5 as a template, and it had problem recognizing the header " YOLOv5 🚀 "

**Comment by fcakyon** [comment]
Yes @LJ-00 emojis may cause issues in yaml file, can you try with minimum required text as in: https://github.com/fcakyon/yolov5-pip/issues/65#issuecomment-986929902?

**Comment by LJ-00** [comment]
Yes, that worked! thanks
