### ISSUE TITLE
Problem during training

### ISSUE THREAD

**Issue by LJ-00** [fcakyon/yolov5-pip#66]
Hello, I am running into the following problem: 

Thanks in advance! 

from yolov5 import train, val, detect, export

train.run(imgsz=640, data='coco128.yaml')
val.run(imgsz=640, data='coco128.yaml', weights='yolov5s.pt')
detect.run(imgsz=640)
export.run(imgsz=640, weights='yolov5s.pt')

  File "C:\Users\anaconda3\envs\torchpip\lib\site-packages\jsonschema\_format.py", line 240, in <module>
    @_checks_drafts(draft7="idn-hostname", raises=idna.IDNAError)

AttributeError: module 'idna' has no attribute 'IDNAError'

**Comment by fcakyon** [comment]
Hello @LJ-00, are you sure you have `coco128.yaml` file present in your local that you give as input?

**Comment by LJ-00** [comment]
That was the issue, sorry. It runs now.

**Comment by fcakyon** [comment]
@LJ-00 glad to hear that! Feel free to open any issues in the future :100:
