### ISSUE TITLE
Memory usage issue question

### ISSUE THREAD

**Issue by LJ-00** [fcakyon/yolov5-pip#67]
Hello! 
I found an issue with this implementation. 
With the ultranalitics implementation I am able to use yolov5x with 4 images of 640. My images are huge and slicing them in small pieces is not an option for me.
Upon using yolov5 with pip, I am only able to use yolo5s with 2 images, same size as before. I have 1 gpu of 11 Gb of memory. 

if I increase the number of images, I get this error: 
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\LJ\anaconda3\envs\yolov5pip\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies

Thank you so much!

**Comment by fcakyon** [comment]
@LJ-00  his repo uses the exact same source code of ultralytics/yolov5. Can you share your code used in ultralytics and yolov5-pip that results in this difference? So that i can recreate the issue and work on a fix.

**Comment by LJ-00** [comment]
If I train from scratch without the weights, it runs well in both pip and ultranalitics. I was doing that in ultranalitics. My dataset is vastly different for the coco dataset, so I thought it was better to not add them. 
Solved.
