### ISSUE TITLE
About .yaml file?

### ISSUE THREAD

**Issue by AI-Hunter** [fcakyon/yolov5-pip#73]
@fcakyon 
Thank for this repo,
Would tell me about the .yaml file please. Previously I have used .cfg.

```
# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)
```
What are 0-P1/2 1-P2/4 ... ? What they mean?

Thanks a lot.

**Comment by fcakyon** [comment]
@AI-Hunter  the P0-P6 output layers are standard names for output layers in vision models.

The idea is simply that the stride = 2^P, i.e. for P6 stride = 2^6 = 64.

A 640x320 image will turn into a 10x5 feature map at stride 64.

Here is an good diagram from the EfficientDet paper:
![effdet](https://user-images.githubusercontent.com/34196005/146692590-9aa0c881-f6e9-49f0-a8b1-cfe9b41ac5dc.png)
