### ISSUE TITLE
convert prediction results from torch.tensor to numpy

### ISSUE THREAD

**Issue by jay0x5** [fcakyon/yolov5-pip#77]
I am trying to use this script with my custom trained yolov5 weights but i am getting this error:

AttributeError: module 'yolov5' has no attribute 'load' 

python version= 3.7.12
yolov5 = 6.06

is this a bug or I am doing something wrong?

**Comment by jay0x5** [comment]
i am running it on colab and here is the script:

import yolov5

# load model
model = yolov5.load('/content/yolov5/runs/train/exp/weights/best.pt')

# set image
img = '/content/data/test/data31.png'

# perform inference
results = model(img)

# inference with larger input size
results = model(img, size=1280)

# inference with test time augmentation
results = model(img, augment=True)

# parse results
predictions = results.pred[0]
boxes = predictions[:, :4] # x1, x2, y1, y2
scores = predictions[:, 4]
categories = predictions[:, 5]

# show detection bounding boxes on image
results.show()

# save results into "results/" folder
results.save(save_dir='results/')

**Comment by fcakyon** [comment]
@jay0x5 i cannot reproduce the error, i get no errors running this snippet:

```python
import yolov5

yolov5.load('yolov5s.pt')
```

Can you post the full error output? Can you give link to your colab so i can test it?

**Comment by fcakyon** [comment]
@jay0x5 are you sure you dont have yolov5 added to your system path? If thats the case you have to remove it from your system path.

**Comment by jay0x5** [comment]
I tried it on my local windows machine
it works! probably some issue with colab notebook
btw i wanted to ask if i can find any tutorial on scaling this code? like printing the predicted class name?
because the basic script doesnt print predictions when i say print(predictions)

**Comment by jay0x5** [comment]
i checked the type of predictions and scores and i wanted to ask if i can convert the tensors into more readable format like string and integer?

**Comment by fcakyon** [comment]
> I tried it on my local windows machine it works! probably some issue with colab notebook btw i wanted to ask if i can find any tutorial on scaling this code? like printing the predicted class name? because the basic script doesnt print predictions when i say print(predictions)

If you want to visualize predictions, your have to run:

```python
import yolov5

model_path='/content/yolov5/runs/train/exp/weights/best.pt'
img = '/content/data/test/data31.png'

model = yolov5.load(model_path)
results = model(img, size=1280)

results.show()
```

**Comment by fcakyon** [comment]
> i checked the type of predictions and scores and i wanted to ask if i can convert the tensors into more readable format like string and integer?

To convert the prediction values into numpy array, you have to run:

```python
import yolov5

model_path='/content/yolov5/runs/train/exp/weights/best.pt'
img = '/content/data/test/data31.png'

model = yolov5.load(model_path)
results = model(img, size=1280)

results.pred[0].tolist()
```

`tolist()` method of torch.tensor, converts the tensor to a numpy array.

**Comment by jay0x5** [comment]
i tried converting torch tensor to numpy array but i got this big error in line  "model = yolov5.load(model_path)
last line says "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect"
Thanks for constant help!
error =>
Traceback (most recent call last):
  File "c:/Users/Jay/Desktop/yolo-data/pipyolo/main.py", line 7, in <module>
    model = yolov5.load(model_path)
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python37\lib\site-packages\yolov5\helpers.py", line 34, in load_model
    attempt_download(model_path)  # download if not found locally
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python37\lib\site-packages\yolov5\utils\google_utils.py", line 43, in attempt_download
    if not file.exists():
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1346, in exists
    self.stat()
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'AutoShape(\n  (model): Model(\n    (model): Sequential(\n      (0): Conv(\n        (conv): Conv2d(3, 32, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2), bias=False)\n        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, 
track_running_stats=True)\n        (act): SiLU()\n      )\n      (1): Conv(\n        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (2): C3(\n        (cv1): Conv(\n          (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)\n    
      (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): 
BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        )\n      )\n      
(3): Conv(\n        (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, 
affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (4): C3(\n        (cv1): Conv(\n          (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n    
    (cv2): Conv(\n          (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n
(conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n          (1): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        
      (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n  
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        
)\n      )\n      (5): Conv(\n        (conv): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (6): C3(\n        (cv1): Conv(\n          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(256, 256, kernel_size=(1, 
1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n          (1): Bottleneck(\n            (cv1): Conv(\n 
             (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n 
           )\n          )\n          (2): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        )\n      )\n      (7): Conv(\n        (conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (8): C3(\n        (cv1): Conv(\n          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n 
         (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n
 (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): 
BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        )\n      )\n      (9): SPPF(\n        (cv1): Conv(\n          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n 
       )\n        (cv2): Conv(\n          (conv): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)\n      )\n      (10): Conv(\n        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (11): Upsample(scale_factor=2.0, mode=nearest)\n      (12): Concat()\n      
(13): C3(\n        (cv1): Conv(\n          (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n    
    (cv3): Conv(\n          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n
(conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        )\n      )\n      (14): Conv(\n        (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n        (bn): BatchNorm2d(128, 
eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (15): Upsample(scale_factor=2.0, mode=nearest)\n      (16): Concat()\n      (17): C3(\n        (cv1): Conv(\n          (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n    
    )\n        (cv3): Conv(\n          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n   
           (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n
   )\n          )\n        )\n      )\n      (18): Conv(\n        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (19): Concat()\n      (20): C3(\n       
 (cv1): Conv(\n          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n       
       (act): SiLU()\n            )\n            (cv2): Conv(\n              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n    
    )\n      )\n      (21): Conv(\n        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n        (act): SiLU()\n      )\n      (22): Concat()\n      (23): C3(\n        (cv1): Conv(\n        
  (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv2): Conv(\n          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n          (act): SiLU()\n        )\n        (cv3): Conv(\n          (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)\n          (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n      
    (act): SiLU()\n        )\n        (m): Sequential(\n          (0): Bottleneck(\n            (cv1): Conv(\n              (conv): Conv2d(256, 256, kernel_size=(1, 
1), stride=(1, 1), bias=False)\n              (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n 
           )\n            (cv2): Conv(\n              (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n              (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)\n              (act): SiLU()\n            )\n          )\n        )\n      )\n      (24): Detect(\n        (m): ModuleList(\n          (0): Conv2d(128, 21, kernel_size=(1, 1), stride=(1, 1))\n          (1): Conv2d(256, 21, kernel_size=(1, 1), stride=(1, 1))\n          (2): Conv2d(512, 21, kernel_size=(1, 1), stride=(1, 1))\n        )\n      )\n    )\n  )\n)'

**Comment by jay0x5** [comment]
Thanks for constant help
i tried to convert to np.array and got this as result
<class 'yolov5.models.common.Detections'> [type]
<yolov5.models.common.Detections object at 0x000001BBFD47DC08> [result]
I wanted to ask if i can retrieve the class name it predicts in a readable format? 
My best wishes for a new year!

**Comment by fcakyon** [comment]
@jay0x5 have you tried `tolist()`? It returns in readable format:

```python
results.pred[0].tolist()

[[751.9083251953125, 45.572418212890625, 1148.55224609375, 716.218017578125, 0.8750465512275696, 0.0], [100.01251220703125, 201.28973388671875, 1002.0526733398438, 718.762939453125, 0.5795167088508606, 0.0], [438.4050598144531, 421.9024658203125, 509.9248352050781, 720.0, 0.5223438143730164, 27.0]]
```

**Comment by fcakyon** [comment]
If you receive empty array, it means model did not predict any object in the given image. You can increase image_size or decrease prediction threshold.

**Comment by jay0x5** [comment]
yes thank you i tried with another image and it returned the values in an array and also made boxes
can i print classname aswell? i have 2 classes "enemy" and "team" so how do i print them based on prediction my model did?

**Comment by fcakyon** [comment]
@jay0x5 class names are stored in `model.names`. So you can get the name of the category 3 as `model.names[3]`.

**Comment by jay0x5** [comment]
thanks but anyway of printing the detected name and not the stored classnames?
like if enemy is detected by model then print only enemy and not a list of all classnames
Thank you

**Comment by fcakyon** [comment]
@jay0x5 as I mentioned earlier `model.names[3]` gives you the category name of 3rd category. It does not give you a list of all categories.

**Comment by jay0x5** [comment]
i tried that but it said list index out of range

**Comment by fcakyon** [comment]
It means your model does not have category id 3. You have to get the category id from prediction result as:

```python
predictions = results.pred[0]
categoriy_ids = predictions[:, 5].tolist()
```

**Comment by jay0x5** [comment]
yes i printed out category_ids and i got this list "[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"

**Comment by jay0x5** [comment]
if i print model.names[1] it gives me "enemy" and if i print model.names[2] it gives me "team"
but how will my program know that model actually detected "team" or "enemy"

**Comment by fcakyon** [comment]
@jay0x5 this is your category id per object:
category_ids = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

you get the category names per object as:
```python
for category_id in category_ids:
    print(model.names[int(category_id)])
```

will print `team` 9 times.

**Comment by jay0x5** [comment]
Thank you very much!!!
now i can know all the predictions
sorry for asking soo many questions
hope you have a great day sir :))
