### ISSUE TITLE
Dockercompose up: No module named 'models.yolo' 

### ISSUE THREAD

**Issue by yktangac** [fcakyon/yolov5-pip#79]
hello, thanks to your work, I'm glad that there is a yolov5 pip package. It's magic, I mean both of yolov5 and this repo are great. I try it on the project I'm working on.
It's a server containing different models for different dataset annotation. 
Every thing works fine in jupyter notebook. However, when it comes to the my current work, it complains that there is no module named model.yolo...

[the code implementation here](https://gist.github.com/yktangac/12cd66e171dbfb8be1fb0d6bc09a10d6)

[screen capture](https://gist.github.com/yktangac/a78409ab4a48a2a5443128d9aff4f902)

terminal output:
```
""Traceback (most recent call last):
""  File "/opt/ml-detector/server.py", line 196, in <module>
""    main(parse_argument())
""  File "/opt/ml-detector/server.py", line 183, in main
""    detector = get_object_detector(**detector_init_params)
""  File "/opt/ml-detector/lib/object_detectors/detector.py", line 61, in get_object_detector
""    detector = PytorchYolov5(**kwargs) 
""  File "/opt/ml-detector/lib/object_detectors/pytorch_yolov5.py", line 11, in __init__
""    self._net = YOLOv5(model)
""  File "/usr/local/lib/python3.6/dist-packages/yolov5/helpers.py", line 60, in __init__
""    self.model = load_model(model_path=model_path, device=device, autoshape=True)
""  File "/usr/local/lib/python3.6/dist-packages/yolov5/helpers.py", line 37, in load_model
""    model = torch.load(model_path, map_location=torch.device(device))
""  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 594, in load
""    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
""  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 853, in _load
     result = unpickler.load()
 ModuleNotFoundError: No module named 'models.yolo'
"""
```

### Environment:
os: ubunut18.04
python version: 3.6
torch vision: 1.7.1
cuda 10.1
cudnn 7.6.5
(dockercompose)🐳

I suspect that there may be a module collision
- detectron2
- yolov5
- openPose
- centernet
- mask-rcnn
(running different models at the same time)
Any suggestion would be helpful 😆

**Comment by fcakyon** [comment]
@yktangac thanks a lot for your innterest!

Prefered way of using this package is:

```python
import yolov5

# load model
model = yolov5.load(weight_path)

# perform inference
results = model(image_path)
```

Have you tried that way?

**Comment by yktangac** [comment]
Yes, I tried both. I'm still figuring out... ar! I finally knew what's going on.
It's because of this  issues: <br> [Module collision when loading more than one model with Torch Hub #5083](https://github.com/ultralytics/yolov5/issues/5083) </br>
<br> [Pytorch Hub issues # 243](https://github.com/pytorch/hub/issues/243) </br>
I tried your way and both with this:
[My Code Implementation for yolov5-pip and pytorch hub ](https://gist.github.com/yktangac/99b1ac971f6974641798122476527abe)<br>
Hopefully, it also helps other !
Again, thanks for your yolov5-pip🤗

**Comment by fcakyon** [comment]
@yktangac have you managed to solve this issue?

**Comment by yktangac** [comment]
Yes, it works. I make a code snippet above for others who may encounter this in future if they're running multiple models in their application.
Not sure whether there may have a better workaround.
```
import sys
sys.modules.pop(${module_you_not_found})
```
Probably create the _intit_paths.py but I didn't try it.
Again, thanks for your help 😆.

**Comment by fcakyon** [comment]
ah i see. thanks a lot for spotting the issue man 🚀
