### ISSUE TITLE
Update to the latest YOLOv5 commit

### ISSUE THREAD

**Issue by LorenzoFerriniCodes** [fcakyon/yolov5-pip#81]
Hi! I am developing an application that relies on the `DetectMultiBackend` class, which the YOLOv5 authors have defined in a more recent commit than the one you have used for your software latest version. Would it be possible to update your code to the latest Ultralytics' YOLOv5 commit? 

Thanks for the big work you're doing here to provide a packaged version of YOLOv5 :)

**Comment by haimat** [comment]
@fcakyon Heyho, any news on this?

**Comment by Paul-Ajay** [comment]
@fcakyon Hi, any update on this

**Comment by fcakyon** [comment]
@LorenzoFerriniCodes @haimat @Paul-Ajay I have updated the package to the latest ultralytics/yolov5 source!

Please update your `yolov5` packages from `040422` branch by `pip install -U git+https://github.com/fcakyon/yolov5-pip.git@040422` and confirm there is no bug.

Once you confirm, I will merge the PR and publish a new release `v6.1.0`!

**Comment by fcakyon** [comment]
@LorenzoFerriniCodes @haimat @Paul-Ajay @severin-lemaignan @kalzeo latest version of the `yolov5` package `v6.1.0` is live covering all the updates from the original `ultralytics/yolov5` repo! 🔥 

Update your yolov5 by `pip install -U yolov5` 🚀

**Comment by haimat** [comment]
Thanks a lot!
