### ISSUE TITLE
Getting different results from hub

### ISSUE THREAD

**Issue by rodrigo2019** [fcakyon/yolov5-pip#84]
Hello, i'm using the pypi package, but the problem is when I use the pypi lib I get different results rather than using the hub.
Also, even setting device to cpu, actually the library allocate some gpu memory, the hub model doesn't.

Could you help me?

```
        # model_plate = torch.hub.load('ultralytics/yolov5', 'custom', path=plate_model_path, device="cpu")
        # model_chars = torch.hub.load('ultralytics/yolov5', 'custom', path=char_model_path, device="cpu")
        model_plate = yolov5.load(plate_model_path, device="cpu")
        model_chars = yolov5.load(char_model_path, device="cpu")
```

**Comment by fcakyon** [comment]
@rodrigo2019 hub model and this package does not use the same version of repo. I will update this repo when I find some time. Follow this thread: https://github.com/fcakyon/yolov5-pip/issues/81
