### ISSUE TITLE
pingback: rikai-yolov5 available

### ISSUE THREAD

**Issue by da-tubi** [fcakyon/yolov5-pip#85]
See https://github.com/Tubitv/rikai-yolov5

And there is a Google Colab notebook for rikai-yolov5:
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Tubitv/rikai-yolov5/blob/main/notebooks/Mojito.ipynb)

Thanks for your awesome work on the packaged yolov5 package.

This issue is a pingback of https://github.com/da-tubi/rikai-example/issues/2

**Comment by fcakyon** [comment]
@da-tubi thanks for notifying! Seems great 💯
