### ISSUE TITLE
How can I print prediction score for each object detected?

### ISSUE THREAD

**Issue by jay0x5** [fcakyon/yolov5-pip#88]
Hello i wanted to know how i can print the prediction score for the detected object? here is my script:

import yolov5
import sys

model = yolov5.load('C:\\Users\\Jay\\Desktop\\YoloV5\\best.pt')

imgpath = "C:\\Users\\Jay\\Desktop\\YoloV5\\Train\\Cube13.jpg"

# img = sys.argv[1]
img = imgpath

results = model(img)

results = model(img, size=1280)

results = model(img, augment=True)

predictions = results.pred[0]
boxes = predictions[:, :4] # x1, x2, y1, y2
scores = predictions[:, 4]
categories = predictions[:, 5]

# results.show()
#print(results.pred[0].tolist()) #will return an empty array if object not detected
predictions = results.pred[0]
category_ids = predictions[:, 5].tolist()
for category_id in category_ids:
    print(model.names[int(category_id)]) #prints detected object name
results.save(save_dir='results/')

If someone can tell me how to then would be a big help, thanks

**Comment by fcakyon** [comment]
it is given in readme: https://github.com/fcakyon/yolov5-pip#use-from-python
