### ISSUE TITLE
Windows GPU no recognition

### ISSUE THREAD

**Issue by koulis-probotek** [fcakyon/yolov5-pip#89]
I am using a Windows PC and when I run the model with GPU it doesn't recognise anything.
If I choose cpu, it works great. Everything was also tested on a new virtual environment.
I've installed yolov5-pip and torch 1.11.0 with Cuda 11.3.

This is the code I am using:
<details>
<summary>mycode.py</summary>

```python
import yolov5
from yolov5.utils.torch_utils import select_device

# load model
# select_device('cpu')
model = yolov5.load('yolov5s.pt')

# set image
img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# perform inference
results = model(img)

# inference with larger input size
results = model(img, size=1280)

# inference with test time augmentation
results = model(img, augment=True)

# parse results
predictions = results.pred[0]
boxes = predictions[:, :4] # x1, y1, x2, y2
scores = predictions[:, 4]
categories = predictions[:, 5]

# show detection bounding boxes on image
results.show()
```
</details>

P.S. I've also tested the original YoloV5 by ultralytics which works both on CPU and GPU, but I really like to use the one you created.

**Comment by fcakyon** [comment]
@koulis-probotek try with `model = yolov5.load('yolov5s.pt', device:'cuda:0')`
