### ISSUE TITLE
Code error in models/common.py

### ISSUE THREAD

**Issue by alvinahmadov** [fcakyon/yolov5-pip#9]
Hello there is a bug in https://github.com/fcakyon/yolov5-pip/blob/1431fe44011c3791647840c8e93fd24215b2db3e/yolov5/models/common.py#L254
Where variable f is not initialized for local image file prediction.
Thank you.

**Comment by fcakyon** [comment]
@alvinahmadov thanks for noticing, fixed this bug + increased test coverage to catch this type of bugs in ci.
