### ISSUE TITLE
Can you update the latestcode from ultralytics/yolov5?

### ISSUE THREAD

**Issue by SethWen** [fcakyon/yolov5-pip#99]
I call yolov5 on production, but the yolov5 set a global logging to root logger,  and  it can not be disabled, which is annoying。
Luckily，the latest code fix it. 
Please see [ttps://github.com/ultralytics/yolov5/pull/7296](url).
Thanks ~

**Comment by fcakyon** [comment]
@SethWen i will update it to latest when i find some time, thanks for pointing out your request 👍

**Comment by fcakyon** [comment]
@SethWen i have added that feature with this pr: https://github.com/fcakyon/yolov5-pip/pull/105

Can you please update your `yolov5` from main branch and see if the issue is solved?

```bash
pip uninstall yolov5
```
```bash
pip install git+https://github.com/fcakyon/yolov5-pip.git
```
